---

  nxos_provider:
    username: "{{ user }}"
    password: "{{ pwd }}"
    transport: nxapi
    host: "{{ inventory_hostname }}"


  features:
  - { feature: bgp }
  - { feature: ospf }
  - { feature: "nv overlay" }
  - { feature: pim }

  l3_interfaces:
  - { interface: Ethernet1/1 }
  - { interface: Ethernet1/2 }
  - { interface: Ethernet1/3 }
  - { interface: Ethernet1/4 }
  - { interface: Ethernet2/1 }
  - { interface: Ethernet2/2 }
  - { interface: Ethernet2/3 }
  - { interface: Ethernet2/4 }

  ospf_process_id: Underlay

  ospf_area: 0
  
  asn: 65001

  address_families:
  - { afi: l2vpn, safi: evpn }
  
  bgp_neighbors:
  - { remote_as: 65001, neighbor: 10.2.2.1, update_source: Loopback0 }
  - { remote_as: 65001, neighbor: 10.2.2.2, update_source: Loopback0 }
  - { remote_as: 65001, neighbor: 10.2.2.3, update_source: Loopback0 }
  - { remote_as: 65001, neighbor: 10.2.2.4, update_source: Loopback0 }

  s1_loopback: 10.2.1.1

  s2_loopback: 10.2.1.2

  rp_address: 100.2.1.1
